clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 49

    # The number of clients selected in each round
    per_round: 5

    # Should the clients compute test accuracy locally?
    do_test: false

    training_time: 13, 18, 4, 4, 19, 11, 2, 6, 19, 3, 8, 3, 5, 5, 10, 14, 14, 13, 6, 2, 14, 20, 16, 20, 15, 5, 15, 19, 17, 9, 13, 12, 20, 18, 15, 11, 11, 9, 10, 10, 7, 16, 14, 3, 12, 6, 14, 16, 5


server:
    address: 127.0.0.1
    port: 8001
    cut_off: 0.7


data:
    # The training and testing dataset
    datasource: CIFAR10
    data_path: ../../datasetsAndModels/CIFAR10_group
    aigc_datasource: aigc_CIFAR10
    aigc_data_path: ../../datasetsAndModels/6

    # Number of samples in each partition
    partition_size: 500

    # server_PC: 0,1
    # server_exp: 0.3
    server_PC: 0,1
    server_exp: 0.2
    
    aigc_speed: 250
    sampler: fpl_customize

    # sampler: fpl_distribution
    # fpl_expectation: 0.4,0.4,0.025,0.025,0.025,0.025,0.025,0.025,0.025,0.025
    # fpl_expectation: 0.3,0.3,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05
    # fpl_expectation: 0.2,0.2,0.075,0.075,0.075,0.075,0.075,0.075,0.075,0.075
    # fpl_expectation: 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1

    # The concentration parameter for the Dirichlet distribution
    # concentration: 0.5

    # The random seed for sampling data
    random_seed: 1

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 50

    # The maximum number of clients running concurrently
    max_concurrency: 1

    # The target accuracy
    target_accuracy: 1

    # The machine learning model
    model_name: resnet_18

    # Number of epoches for local training in each communication round
    epochs: 1
    batch_size: 32
    optimizer: SGD

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    optimizer:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0
        
results:
    result_path: ./FPL_CIFAR10_exp0.4
    # Write the following parameter(s) into a CSV
    types: round, accuracy, elapsed_time, round_time